# Homebrew formula for Pingram CLI.
# Generated by sdks/cli/scripts/package-release.sh — do not edit by hand in the tap.
#
# Public tap repo: pingram-io/homebrew-cli → Formula/pingram.rb
#
#   brew install pingram-io/cli/pingram

class Pingram < Formula
  desc "Official Pingram CLI"
  homepage "https://pingram.io"
  version "1.0.17"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.17/pingram-darwin-arm64.tar.gz"
      sha256 "bffc29f46b44be3780ae1a04b7242ccf6d8cc4f9722d96916525bf1f181013d5"
    end
    on_intel do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.17/pingram-darwin-x64.tar.gz"
      sha256 "89c4bd3e3d1486d1351ee6528dac273d709a2899e119dd1bb859a0f025c03280"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.17/pingram-linux-arm64.tar.gz"
      sha256 "b0c5355e0af26e7e233dfb47b0d77add4e85d00958cb8b9fc7b33719261cd023"
    end
    on_intel do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.17/pingram-linux-x64.tar.gz"
      sha256 "a6dbdbc964db64e3f5a1015d8fe47cb461c546762e499dad31ee308ebe680c1a"
    end
  end

  def install
    bin.install "pingram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pingram --version")
  end
end
