# Homebrew formula for Pingram CLI.
# Generated by sdks/cli/scripts/package-release.sh — do not edit by hand in the tap.
#
# Public tap repo: pingram-io/homebrew-cli → Formula/pingram.rb
#
#   brew install pingram-io/cli/pingram

class Pingram < Formula
  desc "Official Pingram CLI"
  homepage "https://pingram.io"
  version "1.0.19"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.19/pingram-darwin-arm64.tar.gz"
      sha256 "1476cd9989483fabd370d2a9e1957525061a034286d4e0e91ed0c31bb2b28452"
    end
    on_intel do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.19/pingram-darwin-x64.tar.gz"
      sha256 "2665138d03978c5492c10d47cf76d08bb55311d25932d360f92b69bd5e59a18c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.19/pingram-linux-arm64.tar.gz"
      sha256 "c7ed1eecd9d32dcf4f6ff943a39fa5eef9c3c71e3d16483ba5c84991f38c043e"
    end
    on_intel do
      url "https://github.com/pingram-io/cli/releases/download/pingram-cli-v1.0.19/pingram-linux-x64.tar.gz"
      sha256 "70a6a4189132c97f9e1988af9e2636aae87f0b8af8601e41cb9fbf2b8e0e662b"
    end
  end

  def install
    bin.install "pingram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pingram --version")
  end
end
